DROP TABLE if exists STUDENT_SCHEDULEDCLASS;

DROP TABLE if exists SCHEDULEDCLASS;

DROP TABLE if exists COURSE;

DROP TABLE if exists STUDENT;


CREATE TABLE STUDENT (
		ID INT(11) NOT NULL AUTO_INCREMENT,
		NAME VARCHAR(255) NOT NULL,
		PHONENUMBER VARCHAR(20),
		STATUS VARCHAR(20),
	  CONSTRAINT student_pk PRIMARY KEY (id)
	);
	
CREATE TABLE COURSE (
		ID INT NOT NULL AUTO_INCREMENT,
		CODE VARCHAR(20),
		CREDITS DOUBLE NOT NULL,
		TITLE VARCHAR(255),
	  CONSTRAINT course_pk PRIMARY KEY (id)
	);

CREATE TABLE SCHEDULEDCLASS (
		ID INT NOT NULL AUTO_INCREMENT,
		ENDDATE VARCHAR(20),
		STARTDATE VARCHAR(20),
		COURSE_ID INTEGER,
	  CONSTRAINT class_pk PRIMARY KEY (id)
	);

CREATE TABLE STUDENT_SCHEDULEDCLASS (
		STUDENTS_ID INTEGER NOT NULL,
		CLASSES_ID INTEGER NOT NULL
	);

CREATE UNIQUE INDEX SQL150211090953900 ON COURSE (ID ASC);

CREATE INDEX SQL150211090954080 ON STUDENT_SCHEDULEDCLASS (CLASSES_ID ASC);

CREATE INDEX SQL150211090953990 ON SCHEDULEDCLASS (COURSE_ID ASC);

CREATE UNIQUE INDEX SQL150211090953920 ON SCHEDULEDCLASS (ID ASC);

CREATE UNIQUE INDEX SQL150211090953950 ON STUDENT (ID ASC);

CREATE INDEX SQL150211090954040 ON STUDENT_SCHEDULEDCLASS (STUDENTS_ID ASC);

-- ALTER TABLE COURSE ADD CONSTRAINT SQL150211090953900 PRIMARY KEY (ID);

-- ALTER TABLE SCHEDULEDCLASS ADD CONSTRAINT SQL150211090953920 PRIMARY KEY (ID);

-- ALTER TABLE STUDENT ADD CONSTRAINT SQL150211090953950 PRIMARY KEY (ID);

ALTER TABLE STUDENT_SCHEDULEDCLASS ADD CONSTRAINT FK318CA38F83AAB40 FOREIGN KEY (CLASSES_ID)
	REFERENCES SCHEDULEDCLASS (ID);

ALTER TABLE STUDENT_SCHEDULEDCLASS ADD CONSTRAINT FK318CA38F5E4D1BDC FOREIGN KEY (STUDENTS_ID)
	REFERENCES STUDENT (ID);

ALTER TABLE STUDENT_SCHEDULEDCLASS ADD CONSTRAINT NEW_UNIQUE UNIQUE (STUDENTS_ID, CLASSES_ID);

ALTER TABLE SCHEDULEDCLASS ADD CONSTRAINT FKE64C28EBD735B77B FOREIGN KEY (COURSE_ID)
	REFERENCES COURSE (ID);
	


	